"""index foreign keys

Revision ID: 4cd922cf3b04
Revises: 9f169e6f2d40
Create Date: 2026-09-18 15:46:26.760009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd922cf3b04'
down_revision: Union[str, Sequence[str], None] = '9f169e6f2d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_index(op.f('ix_vision_items_category_id'), 'vision_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_vision_items_user_id'), 'vision_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_items_user_id'), table_name='vision_items')
    op.drop_index(op.f('ix_vision_items_category_id'), table_name='vision_items')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    # ### end Alembic commands ###
