"""status enum

Revision ID: 9f169e6f2d40
Revises: 320943feac1e
Create Date: 2026-09-18 15:33:54.073519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f169e6f2d40'
down_revision: Union[str, Sequence[str], None] = '320943feac1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    vision_status = sa.Enum(
        "not_started", "in_progress", "achieved", name="vision_status"
    )
    vision_status.create(op.get_bind())
    op.alter_column('vision_items', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('not_started', 'in_progress', 'achieved', name='vision_status'),
               existing_nullable=False,
               postgresql_using='status::vision_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vision_items', 'status',
               existing_type=sa.Enum('not_started', 'in_progress', 'achieved', name='vision_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum(name="vision_status").drop(op.get_bind())
    # ### end Alembic commands ###
